apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: f8sdd5quc-go 
  janus-idp.io/tekton: f8sdd5quc-go
  backstage.io/kubernetes-id: f8sdd5quc-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: f8sdd5quc-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml