apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f8sdd5quc-go
  janus-idp.io/tekton: f8sdd5quc-go
  backstage.io/kubernetes-id: f8sdd5quc-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: f8sdd5quc-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
